// <auto-generated />
using System;
using LoLTeamSorter.Infra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LoLTeamSorter.Infra.Migrations
{
    [DbContext(typeof(LoLTeamSorterDbContext))]
    [Migration("20250414205619_FullMigrate")]
    partial class FullMigrate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LoLTeamSorter.Domain.Entities.Matchmaking", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BlueTeamId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RedTeamId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BlueTeamId");

                    b.HasIndex("RedTeamId");

                    b.ToTable("Matchmakings");
                });

            modelBuilder.Entity("LoLTeamSorter.Domain.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("MainLane")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("MatchmakingId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RiotId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecondaryLane")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Stars")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MatchmakingId");

                    b.HasIndex("TeamId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("LoLTeamSorter.Domain.Entities.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("LoLTeamSorter.Domain.Entities.Matchmaking", b =>
                {
                    b.HasOne("LoLTeamSorter.Domain.Entities.Team", "BlueTeam")
                        .WithMany()
                        .HasForeignKey("BlueTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LoLTeamSorter.Domain.Entities.Team", "RedTeam")
                        .WithMany()
                        .HasForeignKey("RedTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BlueTeam");

                    b.Navigation("RedTeam");
                });

            modelBuilder.Entity("LoLTeamSorter.Domain.Entities.Player", b =>
                {
                    b.HasOne("LoLTeamSorter.Domain.Entities.Matchmaking", null)
                        .WithMany("Players")
                        .HasForeignKey("MatchmakingId");

                    b.HasOne("LoLTeamSorter.Domain.Entities.Team", null)
                        .WithMany("Players")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("LoLTeamSorter.Domain.ValueObjects.RankedTier", "RankedTier", b1 =>
                        {
                            b1.Property<Guid>("PlayerId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Rank")
                                .HasColumnType("text")
                                .HasColumnName("Rank");

                            b1.Property<string>("Tier")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Tier");

                            b1.HasKey("PlayerId");

                            b1.ToTable("Players");

                            b1.WithOwner()
                                .HasForeignKey("PlayerId");
                        });

                    b.Navigation("RankedTier")
                        .IsRequired();
                });

            modelBuilder.Entity("LoLTeamSorter.Domain.Entities.Matchmaking", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("LoLTeamSorter.Domain.Entities.Team", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
